format:
  revealjs:
    theme: default
    incremental: false
    slide-number: true
    transition: slide
    background-transition: fade
    controls: true
    progress: true
    center: true
    highlight-style: github
